### ISSUE TITLE
Copy example config into the cfg files gives this error 

### ISSUE THREAD

**Issue by tommytusj** [enonic/app-snapshotter#4]
Caused by: java.time.DateTimeException: Invalid value for DayOfWeek: 0
	at java.time.DayOfWeek.of(DayOfWeek.java:165)
	at com.cronutils.descriptor.DescriptionStrategyFactory.lambda$daysOfWeekInstance$0(DescriptionStrategyFactory.java:35)

**Comment by rymsha** [comment]
Can't reproduce on latest version
